
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "reserve-device-enums.h"
#include "plugin.h"
#include "reserve-device.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "reserve-device.h" */

GType
wp_reserve_device_state_get_type (void)
{
    static gsize gtype_id = 0;
    static const GEnumValue values[] = {
        { C_ENUM (WP_RESERVE_DEVICE_STATE_UNKNOWN), "WP_RESERVE_DEVICE_STATE_UNKNOWN", "unknown" },
        { C_ENUM (WP_RESERVE_DEVICE_STATE_BUSY), "WP_RESERVE_DEVICE_STATE_BUSY", "busy" },
        { C_ENUM (WP_RESERVE_DEVICE_STATE_AVAILABLE), "WP_RESERVE_DEVICE_STATE_AVAILABLE", "available" },
        { C_ENUM (WP_RESERVE_DEVICE_STATE_ACQUIRED), "WP_RESERVE_DEVICE_STATE_ACQUIRED", "acquired" },
        { 0, NULL, NULL }
    };
    if (g_once_init_enter (&gtype_id)) {
        GType new_type = g_enum_register_static (g_intern_static_string ("WpReserveDeviceState"), values);
        g_once_init_leave (&gtype_id, new_type);
    }
    return (GType) gtype_id;
}

/* Generated data ends here */

