/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __RESERVE_DEVICE_INTERFACE_H__
#define __RESERVE_DEVICE_INTERFACE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.ReserveDevice1 */

#define WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1 (wp_org_freedesktop_reserve_device1_get_type ())
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1, WpOrgFreedesktopReserveDevice1))
#define WP_IS_ORG_FREEDESKTOP_RESERVE_DEVICE1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1))
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1, WpOrgFreedesktopReserveDevice1Iface))

struct _WpOrgFreedesktopReserveDevice1;
typedef struct _WpOrgFreedesktopReserveDevice1 WpOrgFreedesktopReserveDevice1;
typedef struct _WpOrgFreedesktopReserveDevice1Iface WpOrgFreedesktopReserveDevice1Iface;

struct _WpOrgFreedesktopReserveDevice1Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_request_release) (
    WpOrgFreedesktopReserveDevice1 *object,
    GDBusMethodInvocation *invocation,
    gint arg_priority);

  const gchar * (*get_application_device_name) (WpOrgFreedesktopReserveDevice1 *object);

  const gchar * (*get_application_name) (WpOrgFreedesktopReserveDevice1 *object);

  gint  (*get_priority) (WpOrgFreedesktopReserveDevice1 *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (WpOrgFreedesktopReserveDevice1, g_object_unref)
#endif

GType wp_org_freedesktop_reserve_device1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *wp_org_freedesktop_reserve_device1_interface_info (void);
guint wp_org_freedesktop_reserve_device1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void wp_org_freedesktop_reserve_device1_complete_request_release (
    WpOrgFreedesktopReserveDevice1 *object,
    GDBusMethodInvocation *invocation,
    gboolean result);



/* D-Bus method calls: */
void wp_org_freedesktop_reserve_device1_call_request_release (
    WpOrgFreedesktopReserveDevice1 *proxy,
    gint arg_priority,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean wp_org_freedesktop_reserve_device1_call_request_release_finish (
    WpOrgFreedesktopReserveDevice1 *proxy,
    gboolean* out_result,
    GAsyncResult *res,
    GError **error);

gboolean wp_org_freedesktop_reserve_device1_call_request_release_sync (
    WpOrgFreedesktopReserveDevice1 *proxy,
    gint arg_priority,
    gboolean* out_result,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gint wp_org_freedesktop_reserve_device1_get_priority (WpOrgFreedesktopReserveDevice1 *object);
void wp_org_freedesktop_reserve_device1_set_priority (WpOrgFreedesktopReserveDevice1 *object, gint value);

const gchar *wp_org_freedesktop_reserve_device1_get_application_name (WpOrgFreedesktopReserveDevice1 *object);
gchar *wp_org_freedesktop_reserve_device1_dup_application_name (WpOrgFreedesktopReserveDevice1 *object);
void wp_org_freedesktop_reserve_device1_set_application_name (WpOrgFreedesktopReserveDevice1 *object, const gchar *value);

const gchar *wp_org_freedesktop_reserve_device1_get_application_device_name (WpOrgFreedesktopReserveDevice1 *object);
gchar *wp_org_freedesktop_reserve_device1_dup_application_device_name (WpOrgFreedesktopReserveDevice1 *object);
void wp_org_freedesktop_reserve_device1_set_application_device_name (WpOrgFreedesktopReserveDevice1 *object, const gchar *value);


/* ---- */

#define WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY (wp_org_freedesktop_reserve_device1_proxy_get_type ())
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY, WpOrgFreedesktopReserveDevice1Proxy))
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY, WpOrgFreedesktopReserveDevice1ProxyClass))
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY, WpOrgFreedesktopReserveDevice1ProxyClass))
#define WP_IS_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY))
#define WP_IS_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_PROXY))

typedef struct _WpOrgFreedesktopReserveDevice1Proxy WpOrgFreedesktopReserveDevice1Proxy;
typedef struct _WpOrgFreedesktopReserveDevice1ProxyClass WpOrgFreedesktopReserveDevice1ProxyClass;
typedef struct _WpOrgFreedesktopReserveDevice1ProxyPrivate WpOrgFreedesktopReserveDevice1ProxyPrivate;

struct _WpOrgFreedesktopReserveDevice1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  WpOrgFreedesktopReserveDevice1ProxyPrivate *priv;
};

struct _WpOrgFreedesktopReserveDevice1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType wp_org_freedesktop_reserve_device1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (WpOrgFreedesktopReserveDevice1Proxy, g_object_unref)
#endif

void wp_org_freedesktop_reserve_device1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
WpOrgFreedesktopReserveDevice1 *wp_org_freedesktop_reserve_device1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
WpOrgFreedesktopReserveDevice1 *wp_org_freedesktop_reserve_device1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void wp_org_freedesktop_reserve_device1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
WpOrgFreedesktopReserveDevice1 *wp_org_freedesktop_reserve_device1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
WpOrgFreedesktopReserveDevice1 *wp_org_freedesktop_reserve_device1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON (wp_org_freedesktop_reserve_device1_skeleton_get_type ())
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON, WpOrgFreedesktopReserveDevice1Skeleton))
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON, WpOrgFreedesktopReserveDevice1SkeletonClass))
#define WP_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON, WpOrgFreedesktopReserveDevice1SkeletonClass))
#define WP_IS_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON))
#define WP_IS_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), WP_TYPE_ORG_FREEDESKTOP_RESERVE_DEVICE1_SKELETON))

typedef struct _WpOrgFreedesktopReserveDevice1Skeleton WpOrgFreedesktopReserveDevice1Skeleton;
typedef struct _WpOrgFreedesktopReserveDevice1SkeletonClass WpOrgFreedesktopReserveDevice1SkeletonClass;
typedef struct _WpOrgFreedesktopReserveDevice1SkeletonPrivate WpOrgFreedesktopReserveDevice1SkeletonPrivate;

struct _WpOrgFreedesktopReserveDevice1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  WpOrgFreedesktopReserveDevice1SkeletonPrivate *priv;
};

struct _WpOrgFreedesktopReserveDevice1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType wp_org_freedesktop_reserve_device1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (WpOrgFreedesktopReserveDevice1Skeleton, g_object_unref)
#endif

WpOrgFreedesktopReserveDevice1 *wp_org_freedesktop_reserve_device1_skeleton_new (void);


G_END_DECLS

#endif /* __RESERVE_DEVICE_INTERFACE_H__ */
