
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "dbus-connection-enums.h"
#include "dbus-connection-state.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "dbus-connection-state.h" */

GType
wp_dbus_connection_state_get_type (void)
{
    static gsize gtype_id = 0;
    static const GEnumValue values[] = {
        { C_ENUM (WP_DBUS_CONNECTION_STATE_CLOSED), "WP_DBUS_CONNECTION_STATE_CLOSED", "closed" },
        { C_ENUM (WP_DBUS_CONNECTION_STATE_CONNECTING), "WP_DBUS_CONNECTION_STATE_CONNECTING", "connecting" },
        { C_ENUM (WP_DBUS_CONNECTION_STATE_CONNECTED), "WP_DBUS_CONNECTION_STATE_CONNECTED", "connected" },
        { 0, NULL, NULL }
    };
    if (g_once_init_enter (&gtype_id)) {
        GType new_type = g_enum_register_static (g_intern_static_string ("WpDBusConnectionState"), values);
        g_once_init_leave (&gtype_id, new_type);
    }
    return (GType) gtype_id;
}

/* Generated data ends here */

