
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "dbus-connection-state.h" */

GType wp_dbus_connection_state_get_type (void);
#define WP_TYPE_DBUS_CONNECTION_STATE (wp_dbus_connection_state_get_type())

G_END_DECLS

/* Generated data ends here */

