/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "pipewire"

#undef HAVE_ALSA_COMPRESS_OFFLOAD

#undef HAVE_DBUS

#undef HAVE_FFTW

#undef HAVE_GETRANDOM

#define HAVE_GETTID

#undef HAVE_GLIB2

#define HAVE_GRP_H

#undef HAVE_GSTREAMER_DEVICE_PROVIDER

#undef HAVE_GSTREAMER_DMA_DRM

#undef HAVE_GSTREAMER_SHM_ALLOCATOR

#undef HAVE_LIBUDEV

#undef HAVE_LIBUSB

#undef HAVE_LOGIND

#define HAVE_MALLOC_INFO

#undef HAVE_MALLOC_TRIM

#undef HAVE_MEMFD_CREATE

#undef HAVE_OPUS

#define HAVE_PIDFD_OPEN

#define HAVE_PWD_H

#undef HAVE_PW_CAT_FFMPEG_INTEGRATION

#undef HAVE_RANDOM_R

#undef HAVE_READLINE

#undef HAVE_REALLOCARRAY

#undef HAVE_SELINUX

#undef HAVE_SIGABBREV_NP

#undef HAVE_SNDFILE

#define HAVE_SPA_PLUGINS

#undef HAVE_SYSTEMD

#define HAVE_SYS_AUXV_H

#define HAVE_SYS_MOUNT_H

#define HAVE_SYS_PARAM_H

#define HAVE_SYS_RANDOM_H

#define HAVE_SYS_VFS_H

#undef HAVE_XFIXES_6

#undef HAVE_XSETIOERROREXITHANDLER

#define LIBDIR "/data/data/com.termux/files/usr/lib"

#define LOCALEDIR "/data/data/com.termux/files/usr/share/locale"

#define MODULEDIR "/data/data/com.termux/files/usr/lib/pipewire-0.3"

#define PACKAGE "pipewire"

#define PACKAGE_NAME "PipeWire"

#define PACKAGE_STRING "PipeWire 1.6.7"

#define PACKAGE_TARNAME "pipewire"

#define PACKAGE_URL "https://pipewire.org"

#define PACKAGE_VERSION "1.6.7"

#define PA_ALSA_DATA_DIR "/data/data/com.termux/files/usr/share/alsa-card-profile/mixer"

#define PIPEWIRE_CONFDATADIR "/data/data/com.termux/files/usr/share/pipewire"

#define PIPEWIRE_CONFIG_DIR "/data/data/com.termux/files/usr/etc/pipewire"

#define PLUGINDIR "/data/data/com.termux/files/usr/lib/spa-0.2"

#define PREFIX "/data/data/com.termux/files/usr"

#define RTPRIO_CLIENT 83

#define RTPRIO_SERVER 88

#define SPADATADIR "/data/data/com.termux/files/usr/share/spa-0.2"

