/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BUILD_DATADIR "/data/data/com.termux/files/usr/share"

#define BUILD_LIBDIR "/data/data/com.termux/files/usr/lib"

#define BUILD_LOCALEDIR "/data/data/com.termux/files/usr/share/locale"

#define BUILD_SYSCONFDIR "/data/data/com.termux/files/usr/etc"

